### ISSUE TITLE
Limpiar json syft

### ISSUE THREAD

**Issue by Ardark27** [osoc-es/c2t#3]

**Comment by dgarijo** [comment]
Missing documentation and usage for this

**Comment by Ardark27** [comment]
Que documentación se puede crear para un script de parse?

**Comment by dgarijo** [comment]
- Cómo se instala
- Cómo se invoca.
- Qué parametros tiene

**Comment by Ardark27** [comment]
Pero no se instala, y se llama desde la cli, los parámetros están dentro del docustring de la función

**Comment by dgarijo** [comment]
entonces ya está
